package net.parttimepolymath;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.util.Map;

/**
 * API gateway handler. Liberally stolen from https://github.com/awsdocs/aws-lambda-developer-guide
 */
public class Handler implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {
    private Gson gson = new GsonBuilder().setPrettyPrinting().create();

    @Override
    public APIGatewayV2HTTPResponse handleRequest(final APIGatewayV2HTTPEvent event, final Context context) {
        APIGatewayV2HTTPResponse response = APIGatewayV2HTTPResponse.builder()
                .withIsBase64Encoded(false)
                .withStatusCode(200)
                .withHeaders(Map.of("Content-Type", "text/html"))
                .withBody("<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>"+
                        "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" +
                        "</body></html>")
                .build();

        Util.logEnvironment(event, context, gson);

        return response;
    }
}
