package net.parttimepolymath;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;

import java.util.Map;

/**
 * API gateway handler.
 * @author Robert
 * @since 21/05/2021
 */
public class Handler implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    @Override
    public APIGatewayV2HTTPResponse handleRequest(final APIGatewayV2HTTPEvent event, final Context context) {
        LambdaLogger logger = context.getLogger();

        ParsedEvent parsedEvent = new ParsedEvent(event);
        logger.log(parsedEvent.toString());

        APIGatewayV2HTTPResponse response = APIGatewayV2HTTPResponse.builder()
                .withIsBase64Encoded(false)
                .withStatusCode(200)
                .withHeaders(Map.of("Content-Type", "text/html"))
                .withBody("<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>"+
                        "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" +
                        "</body></html>")
                .build();

        return response;
    }
}
